name: Event Bot

on:
  issues:
    types: [opened, edited]

jobs:
  process-event:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'event')
    permissions:
      contents: write
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Process event issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY: ${{ toJSON(github.event.issue.body) }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: python .github/scripts/process_event_issue.py
